if (ENABLE_CLANG_TIDY)
  find_program(CLANGTIDY clang-tidy)
  if(CLANGTIDY)
    set(CMAKE_CXX_CLANG_TIDY ${CLANGTIDY})
    message(STATUS "Clang-Tidy finished setting up")
  else()
    message(SEND_ERROR "Clang-Tidy requested but executable not found")
  endif()
endif()
